// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// Kmer_matrix
IntegerMatrix Kmer_matrix(SEXP seqs, int K);
RcppExport SEXP Kmer_Kmer_matrix(SEXP seqsSEXP, SEXP KSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< SEXP >::type seqs(seqsSEXP );
        Rcpp::traits::input_parameter< int >::type K(KSEXP );
        IntegerMatrix __result = Kmer_matrix(seqs, K);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
