# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Kmer_matrix <- function(seqs, K, names) {
    .Call('Kmer_Kmer_matrix', PACKAGE = 'Kmer', seqs, K, names)
}

